/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EvenNumbers;

import javax.swing.*;

public class App {
    

    public static void main(String[] args) {
            String input;
            String[] evenNumber = new String[10];
        
        for(int i = 0; i<evenNumber.length; i++){
         //Get user input   
        input = JOptionPane.showInputDialog("Enter Any Number");
        
        //Convert to integer 
        int value = Integer.parseInt(input);
        
        //Check if even number 
        if(value % 2 == 0){
            evenNumber[i] = input;
            }
        }
        
        JOptionPane.showMessageDialog(null, evenNumber);
    }
}
